### ISSUE TITLE
more doc please !

### ISSUE THREAD

**Issue by Offirmo** [zzmp/dbug#2]
What does this do exactly ? Please expand the README.

**Comment by zzmp** [comment]
Working on it tonight! I'll close the issue when the docs are complete so you're updated.

**Comment by zzmp** [comment]
@Offirmo hope these help!

I haven't gotten a chance to test yet and it's 1:45AM, so I'll give it another pass tomorrow to make sure that it works.

I hope that these docs are enough to go on for now.
